import { Image } from "react-native";

/**
 * AuroraGlyph — the homeowner lens's 2nd-tab button (replaces the PI glyph). One Aurora
 * orb in the Builder's Open House palette (teal #14B8A6 · cyan #06B6D4 · emerald #10B981),
 * generated by scripts/gen-aurora-glyph.mjs → assets/aurora-glyph.png (pick a different
 * aurora-glyph-{1..4}.png variant by copying it over the canonical file). A raster glyph
 * can't be color-tinted, so it dims via opacity when the tab is unfocused.
 */
export function AuroraGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/aurora-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, borderRadius: size / 2, opacity: focused ? 1 : 0.55 }}
    />
  );
}
