import { Image } from "react-native";

/**
 * CockpitGlyph — the Custodian Cockpit tab glyph (custodian lens only). A Custodian-gold
 * (#FFE500) apex/console emblem, generated by scripts/gen-cockpit-glyph.mjs →
 * assets/cockpit-glyph.png (pick a different cockpit-glyph-{1..3}.png variant by copying
 * it over the canonical file). A raster glyph can't be color-tinted, so it dims via
 * opacity when the tab is unfocused.
 */
export function CockpitGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/cockpit-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
