import { Image } from "react-native";

/**
 * HubGlyph — the Hub bottom-tab glyph (shown in every view-mode). A nano-banana (Gemini image)
 * render of PI's "Lucent" home mark: a glowing green orb grounded in roots — the same emblem the
 * drawer shows next to "Hub" (components/side-bar.tsx, icon:"lucent"). Generated by
 * scripts/gen-hub-glyph.mjs → assets/hub-glyph.png. A raster glyph can't be color-tinted, so it
 * dims via opacity when the tab is unfocused.
 */
export function HubGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/hub-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
