import { Image } from "react-native";

/**
 * NeighborsGlyph — the Neighbors bottom-tab glyph. A nano-banana (Gemini image)
 * render of connected home rooftops (assets/neighbors-glyph.png, generated by
 * scripts/gen-neighbors-glyph.mjs). A raster glyph can't be color-tinted, so it
 * dims via opacity when the tab is unfocused.
 */
export function NeighborsGlyph({ size = 22, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/neighbors-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
