import { Image } from "react-native";

/**
 * PiGlyph — the PI bottom-tab glyph (homeowner lens). A nano-banana (Gemini) image-to-image render
 * that distills PI's picture (assets/avatars/scenes/pi/idle.png) down to his glowing green lens-EYE
 * emblem, generated by scripts/gen-pi-glyph.mjs → assets/pi-glyph.png. A raster glyph can't be
 * color-tinted, so it dims via opacity when the tab is unfocused.
 */
export function PiGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/pi-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
