import { Image } from "react-native";

/**
 * ProfileGlyph — the Profile bottom-tab glyph. A nano-banana (Gemini image) render of
 * the person at the center of the system: a constellation bust with a gold rim and an
 * emerald core, inside a gold ring (the human = gold, per the Custodian lore).
 * Generated by scripts/gen-profile-glyph.mjs → assets/profile-glyph.png. A raster glyph
 * can't be color-tinted, so it dims via opacity when the tab is unfocused.
 */
export function ProfileGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/profile-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
