import { Image } from "react-native";

/**
 * VCHomesGlyph — the VC Homes tab glyph (custodian lens only). The value chain
 * itself: a violet (#8B5CF6) DNA double helix entwined through a home, generated by
 * scripts/gen-vc-homes-glyph.mjs → assets/vc-homes-glyph.png (pick a different
 * vc-homes-glyph-{1..3}.png variant by copying it over the canonical file). A raster
 * glyph can't be color-tinted, so it dims via opacity when the tab is unfocused.
 */
export function VCHomesGlyph({ size = 24, focused = true }: { size?: number; focused?: boolean }) {
  return (
    <Image
      source={require("../assets/vc-homes-glyph.png")}
      resizeMode="contain"
      style={{ width: size, height: size, opacity: focused ? 1 : 0.55 }}
    />
  );
}
